#!/usr/bin/env bash

# Binding to reload the configuration (good for edits on bindings or adding new stuff
riverctl map normal "Mod4" R spawn $HOME/.config/river/init

# Include keybindings
riverctl spawn $HOME/.config/river/keybindings.sh

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75
