#!/usr/bin/env bash

# Set keyboard layout. See man riverctl
# riverctl keyboard-layout -options "grp:caps_toggle" "us,ru"

# Binding to reload the configuration (good for edits on bindings or adding new stuff
riverctl map normal "Mod4" R spawn $HOME/.config/river/init

# Polkit agent
riverctl spawn "/usr/bin/mate-polkit"

# Wallpaper
riverctl spawn $HOME/.azotebg

# Waybar
riverctl spawn $HOME/.config/river/waybar.sh

# Include keybindings
riverctl spawn $HOME/.config/river/keybindings.sh

# Clipboard daemon
pkill wl-paste
wl-paste --watch cliphist store & disown
wl-paste --watch pkill -RTMIN+9 waybar & disown

# Playerctl daemon
pkill playerctl
playerctl -a metadata --format \'{{status}} {{title}}\' --follow | while read line; do pkill -RTMIN+5 waybar; done & disown

# Run nwg-drawer as a daemon
pkill nwg-drawer
nwg-drawer -r & disown

# Screenshot notification
riverctl spawn /usr/share/river/scripts/screenshot-notify.sh & disown

# Lock screen daemon
riverctl spawn $HOME/.config/river/screenlock.sh

# Poweralertd daemon
pkill poweralertd
poweralertd -s -i "line power" & disown

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x8aadf4
riverctl border-color-unfocused 0xa5adcb
riverctl border-width 2

# Import environment variables to D-Bus and systemd
VARIABLES="DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE"

exec systemctl --user import-environment $VARIABLES

if hash dbus-update-activation-environment 2>/dev/null; then
    exec dbus-update-activation-environment --systemd ${VARIABLES:- --all}
fi
